# Generated by Django 5.2 on 2025-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_blogpost_votes_comment_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="value",
        ),
        migrations.AddField(
            model_name="vote",
            name="is_life",
            field=models.BooleanField(default=True),
        ),
    ]
