# Generated by Django 5.2 on 2025-04-11 21:43

from django.db import migrations

def convert_votes_to_lives(apps, schema_editor):
    # Get the historical version of the Vote model
    Vote = apps.get_model('core', 'Vote')
    BlogPost = apps.get_model('core', 'BlogPost')
    
    # Update votes to lives
    for post in BlogPost.objects.all():
        # Count all votes that are true (is_life=True)
        lives_count = Vote.objects.filter(post=post, is_life=True).count()
        post.votes = lives_count
        post.save()

def revert_lives_to_votes(apps, schema_editor):
    # This is a no-op since we can't restore the old vote values
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_vote_value_vote_is_life"),
    ]

    operations = [
        migrations.RunPython(convert_votes_to_lives, revert_lives_to_votes),
    ]
