# Generated by Django 5.1.6 on 2025-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_convert_votes_to_lives"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
    ]
