# Generated by Django 5.2 on 2025-04-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
